'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

   return queryInterface.bulkInsert('Items', [
     {
    name: 'Chimes',
    shortDescription: 'Some beautiful jangly chimes for the wind to play with.',
    longDescription: 'Windchimes made by my mom, who has never made windchimes before but somehow managed to create these beautiful things. When the wind rises they sing like clashing pots. What a wonderful sound.',
    price: 30.00,
    sellerId: 1,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_5.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_6.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_7.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Chimes/chimes_8.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dragonfruit',
    shortDescription: 'Tasty tasty fruit',
    longDescription: 'I started growing these for fun but now I have far too many, so I have chosen to sell them. Goodbye my dear dragonfruits.',
    price: 7.00,
    sellerId: 2,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_5.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_6.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_7.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Dragonfruit/dragonfruit_8.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ducks',
    shortDescription: 'QUACK.',
    longDescription: 'Lots and lots and lots and lots and lots and lots and lots and lots and lots and lots and lots and lots and lots and lots and lots and lots of DUCKS.',
    price: 100.00,
    sellerId: 3,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Ducks/ducks_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Ducks/ducks_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Ducks/ducks_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Ducks/ducks_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Ducks/ducks_4.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Fake Plant Things',
    shortDescription: 'Spiky fake plants. Almost kind of pretty.',
    longDescription: 'I made these to ward of predators but I think they look decent as decorations as well.',
    price: 65.99,
    sellerId: 4,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/FakePlants/plant_1_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/FakePlants/plant_1_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/FakePlants/plant_1_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/FakePlants/plant_1_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/FakePlants/plant_1_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/FakePlants/plant_1_5.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Picure Frames',
    shortDescription: 'Gorgeous multicolor frames.',
    longDescription: 'I wove these by hand over three years. Each one took me just under 300 hours and every second was an absolute joy. ',
    price: 500.00,
    sellerId: 6,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Frames/photo_frames_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Frames/photo_frames_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Frames/photo_frames_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Frames/photo_frames_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Frames/photo_frames_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Frames/photo_frames_5.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Frames/photo_frames_6.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Garden Stuff',
    shortDescription: 'Just random stuff. For the garden',
    longDescription: 'I do not even have a garden. Never have. Not sure I ever wanted one. But here is some stuff anyway' ,
    price: 12.00,
    sellerId: 1,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/GardenStuff/solar_thing_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/GardenStuff/solar_thing_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/GardenStuff/solar_thing_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/GardenStuff/solar_thing_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/GardenStuff/solar_thing_4.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gnome',
    shortDescription: 'Short bearded lawn goblins.',
    longDescription: 'I have a fear of gnomes, but I tried to overcome it by building these. It did not work and now there are too many of them. Please buy them all.',
    price: 34.00,
    sellerId: 5,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/gnome/gnome_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/gnome/gnome_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/gnome/gnome_2.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Grapefruit',
    shortDescription: 'Sour. Not at all like grapes.',
    longDescription: 'They are so large. They have consumed the entirety of my counter space.',
    price: 643.00,
    sellerId: 6,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/GrapeFruits/grapefruit_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/GrapeFruits/grapefruit_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/GrapeFruits/grapefruit_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/GrapeFruits/grapefruit_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/GrapeFruits/grapefruit_4.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Jackfruit (not to be confused with Jillfruit)',
    shortDescription: 'A larfe fruit. Named after my uncle Jack',
    longDescription: 'It comes in a box, which is pretty much the main feature here. If you have a cat the cat can sit. If you have things to carry the box can assist. Trust me, come for the fruit, stay for the box.',
    price: 5634.00,
    sellerId: 4,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Jackfruit/jackfruit_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Jackfruit/jackfruit_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Jackfruit/jackfruit_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Jackfruit/jackfruit_3.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Keychain',
    shortDescription: 'An off the chain keychain.',
    longDescription: 'You can hold keys on keys. As many keys as you can think of. Think of 59 keys. You bet this chain can hold them',
    price: 6.04,
    sellerId: 3,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_5.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_6.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_7.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Keychain (COOL AND FUN)',
    shortDescription: 'An off the chain keychain.',
    longDescription: 'You can hold keys on keys. As many keys as you can think of. Think of 59 keys. You bet this chain can hold them',
    price: 6.04,
    sellerId: 3,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_2_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_2_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_2_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_2_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Keychain/keychain_2_4.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'LED Light Strip',
    shortDescription: 'Bright colorful lights.',
    longDescription: 'Do you like to party? Well these are the lights for YOU. They have RED, GREEN, BLUE, and EVERY COLOR BETWEEN.',
    price: 345.00,
    sellerId: 5,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_5.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_6.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_7.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_8.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_9.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/LightStrip/led_strip_10.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'COOL NEON LIGHT',
    shortDescription: 'This light is an absolute vibe.',
    longDescription: 'Windchimes made by my mom, who has never made windchimes before but somehow managed to create these beautiful things. When the wind rises they sing like clashing pots. What a wonderful sound.',
    price: 3454.00,
    sellerId: 2,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/NeonLight/neon_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/NeonLight/neon_1.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Octopus',
    shortDescription: "What's better than 7 legs??? 8!",
    longDescription: 'This little guy is a land octpus that sits in your yard and looks pretty. ',
    price: 1.00,
    sellerId: 1,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Octopus/octopus_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Octopus/octopus_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Octopus/octopus_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Octopus/octopus_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Octopus/octopus_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Octopus/octopus_5.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Handmade Rug',
    shortDescription: 'For looking at, not stepping on.',
    longDescription: 'A wonderful authentic rug.',
    price: 546.34,
    sellerId: 6,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Rug/rug_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/Rug/rug_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Rug/rug_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Rug/rug_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/Rug/rug_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Rug/rug_5.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/Rug/rug_6.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Shoe Rack for Sick Kicks',
    shortDescription: 'Let your shoes rest on this masterpiece.',
    longDescription: 'I have 3000 pairs of shoes. I literally live in a house of shoes because I spent all my money on shoes. This shoe holder is definitely the pinnacle of shoe reacks. Your kicks will love you. They will carress your feet in ways that they never have before.' ,
    price: 90.67,
    sellerId: 4,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/ShoeRack/shoe_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/ShoeRack/shoe_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/ShoeRack/shoe_2.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/ShoeRack/shoe_3.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/ShoeRack/shoe_4.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ultra Mini Shovel!',
    shortDescription: 'Have you ever seen a shovel so small.',
    longDescription: 'Do you like to dig holes? Big holes, small holes, medium holes? Holes for plants or seeds or just...holes? Well this little guy can help you out. He digs holes. So many holes. My whole yard is covered in them, and now your can be too! With this tiny tiny shovel.',
    price: 87.87,
    sellerId: 1,
    thumbnail: 'https://aasourcebucket.s3.us-east-2.amazonaws.com/trowel/trowel_1.jpg',
    photos: ['https://aasourcebucket.s3.us-east-2.amazonaws.com/trowel/trowel_1.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/trowel/trowel_2.jpg', 'https://aasourcebucket.s3.us-east-2.amazonaws.com/trowel/trowel_3.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/trowel/trowel_4.jpg','https://aasourcebucket.s3.us-east-2.amazonaws.com/trowel/trowel_5.jpg'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Items', null, {});
  }
};
